### ISSUE TITLE
Errors & restarting file generation

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/tree-build#33]
I followed the instructions for creating the filtered files, and got:

```
INFO:root:Finished generating file Wiki/wd_JSON/OneZoom_latest-all.json
INFO:root:Generating file Wiki/wp_SQL/OneZoom_enwiki-latest-page.sql
Traceback (most recent call last):
  File "/Users/yan/mambaforge/bin/generate_filtered_files", line 33, in <module>
    sys.exit(load_entry_point('oz-tree-build', 'console_scripts', 'generate_filtered_files')())
  File "/Users/yan/Documents/GitHub/tree-build/oz_tree_build/utilities/generate_filtered_files.py", line 519, in main
    process_args(args)
  File "/Users/yan/Documents/GitHub/tree-build/oz_tree_build/utilities/generate_filtered_files.py", line 459, in process_args
    generate_all_filtered_files(
  File "/Users/yan/Documents/GitHub/tree-build/oz_tree_build/utilities/generate_filtered_files.py", line 434, in generate_all_filtered_files
    generate_and_cache_filtered_file(
  File "/Users/yan/Documents/GitHub/tree-build/oz_tree_build/utilities/generate_filtered_files.py", line 73, in generate_and_cache_filtered_file
    processing_function(original_file, clade_filtered_file, context)
  File "/Users/yan/Documents/GitHub/tree-build/oz_tree_build/utilities/generate_filtered_files.py", line 328, in generate_filtered_wikipedia_sql_dump
    with open_file_based_on_extension(
  File "/Users/yan/Documents/GitHub/tree-build/oz_tree_build/utilities/file_utils.py", line 20, in open_file_based_on_extension
    return open(filename, mode, encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: 'Wiki/wp_SQL/OneZoom_enwiki-latest-page.sql'
[2]  + exit 1     generate_filtered_files OZTreeBuild/AllLife/AllLife_full_tree.phy     
```

I think this is my fault, and I just need to add a missing file. But I don't want to have to re-run the wd_JSON filtering, which took a day on my machine. It's not clear to me whether or how I can rerun without repeating the steps that have already been done.

**Comment by hyanwong** [comment]
Ah, perfect. It may be worth noting this in the instructions?

**Comment by hyanwong** [comment]
(and yes, I do have both files)

**Comment by davidebbo** [comment]
> Ah, perfect. It may be worth noting this in the instructions?

Indeed, and I just did add a paragraph in that section before the command.

**Comment by hyanwong** [comment]
My error was that I accidentally named the SQL directory `wd_SQL` not `wp_SQL`. I think it would be useful to commit a .gitignore in each of the wd_ and wp_ directories so that they are forced to exist on GH. What do you think @davidebbo ?

**Comment by hyanwong** [comment]
> > Ah, perfect. It may be worth noting this in the instructions?
> 
> Indeed, and I just did add a paragraph in that section before the command.

Great, thanks. Sorry if I missed that.

**Comment by davidebbo** [comment]
> My error was that I accidentally named the SQL directory `wd_SQL` not `wp_SQL`. I think it would be useful to commit a .gitignore in each of the wd_ and wp_ directories so that they are forced to exist on GH. What do you think @davidebbo ?

Yes, that's definitely helpful. Added via #34
